language: python
python:
  - "2.6"
  - "2.7"
node_js:
  - "0.10"
services:
  - riak
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo wget -O - http://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
  - sudo echo 'deb http://debian.neo4j.org/repo stable/' > /etc/apt/sources.list.d/neo4j.list
  - sudo aptitude update -y
  - sudo aptitude install neo4j -y
  - sudo service neo4j-service start
install:
  - "pip install coveralls --use-wheel"
  - "pip install -e ."
script:
  - coverage run --source=archer `which trial` archer
after_success:
  - coveralls
